-- ============================================================
-- GameEarn — seed data
-- Generated from the site's existing dummy catalog (data/games.js)
-- so no existing game information is lost in the migration to
-- Supabase. All 28 games are seeded as status = 'published' so
-- the public site keeps working immediately after this runs.
--
-- Run this AFTER supabase/schema.sql, in the Supabase SQL Editor.
-- Safe to re-run: it upserts on the unique slug.
-- ============================================================

insert into public.games
  (name, slug, description, category, genre, rating, platform, developer,
   version, size, release_date, image_url, icon_url, screenshots, source_url,
   reward_type, free_to_play, featured, trending, popular, new_release, status)
values
  ('CoinDash Runner', 'coindash-runner', 'An endless runner where in-game coins collected during timed events can be redeemed through the developer''s own rewards program. Sessions are short, built for one-handed play on a commute.', 'earning-games', 'Runner', 4.3, 'Android, iOS', 'Loop Interactive', '3.2.1', '128 MB', '2023-02-14', '/assets/games/coindash-runner-cover.svg', '/assets/games/coindash-runner-icon.svg', '["/assets/games/coindash-runner-shot-1.svg","/assets/games/coindash-runner-shot-2.svg","/assets/games/coindash-runner-shot-3.svg"]'::jsonb, 'https://example.com/source/coindash-runner', 'Points', true, true, true, true, false, 'published'),
  ('Trivia Vault', 'trivia-vault', 'A daily trivia app across six categories. Correct streaks unlock entries into scheduled prize draws that are managed and awarded directly by the publisher.', 'reward-apps', 'Trivia', 4.1, 'Android, iOS', 'Vault Games Ltd.', '1.9.0', '64 MB', '2024-05-01', '/assets/games/trivia-vault-cover.svg', '/assets/games/trivia-vault-icon.svg', '["/assets/games/trivia-vault-shot-1.svg","/assets/games/trivia-vault-shot-2.svg","/assets/games/trivia-vault-shot-3.svg"]'::jsonb, 'https://example.com/source/trivia-vault', 'Gift Cards', true, true, false, true, false, 'published'),
  ('Blade Reckoning', 'blade-reckoning', 'A stylized 3D hack-and-slash with combo-driven combat, seasonal bosses and a cosmetic-only progression system. No rewards program is attached to this title.', 'action', 'Hack and Slash', 4.6, 'Android, iOS, Windows', 'Ironvale Studio', '2.4.0', '1.8 GB', '2022-11-09', '/assets/games/blade-reckoning-cover.svg', '/assets/games/blade-reckoning-icon.svg', '["/assets/games/blade-reckoning-shot-1.svg","/assets/games/blade-reckoning-shot-2.svg","/assets/games/blade-reckoning-shot-3.svg"]'::jsonb, 'https://example.com/source/blade-reckoning', 'None', true, true, true, true, false, 'published'),
  ('Nitro Circuit GP', 'nitro-circuit-gp', 'Arcade-style circuit racing with drift physics and a weekly leaderboard. Top leaderboard finishers become eligible for tournament rewards defined by the publisher''s seasonal event terms.', 'racing', 'Arcade Racing', 4.4, 'Android, iOS', 'Redline Games', '4.0.3', '950 MB', '2023-08-22', '/assets/games/nitro-circuit-gp-cover.svg', '/assets/games/nitro-circuit-gp-icon.svg', '["/assets/games/nitro-circuit-gp-shot-1.svg","/assets/games/nitro-circuit-gp-shot-2.svg","/assets/games/nitro-circuit-gp-shot-3.svg"]'::jsonb, 'https://example.com/source/nitro-circuit-gp', 'Tournament Rewards', true, false, true, true, false, 'published'),
  ('Pixel Pitch Manager', 'pixel-pitch-manager', 'A retro-styled football management sim. Build a squad, run a season, and compete in ranked leagues with cosmetic trophies.', 'sports', 'Sports Management', 4.2, 'Android', '8-Bit Pitch', '1.5.2', '210 MB', '2024-01-30', '/assets/games/pixel-pitch-manager-cover.svg', '/assets/games/pixel-pitch-manager-icon.svg', '["/assets/games/pixel-pitch-manager-shot-1.svg","/assets/games/pixel-pitch-manager-shot-2.svg","/assets/games/pixel-pitch-manager-shot-3.svg"]'::jsonb, 'https://example.com/source/pixel-pitch-manager', 'None', true, false, false, true, false, 'published'),
  ('Kingdom Ledger', 'kingdom-ledger', 'A slow-burn strategy title about managing a medieval trade kingdom. Weekly tournaments run by the developer offer in-game reward chests to top-ranked alliances.', 'strategy', '4X Strategy', 4.5, 'Android, iOS, Windows', 'Longhall Interactive', '5.1.0', '1.2 GB', '2021-06-18', '/assets/games/kingdom-ledger-cover.svg', '/assets/games/kingdom-ledger-icon.svg', '["/assets/games/kingdom-ledger-shot-1.svg","/assets/games/kingdom-ledger-shot-2.svg","/assets/games/kingdom-ledger-shot-3.svg"]'::jsonb, 'https://example.com/source/kingdom-ledger', 'In-game Rewards', true, true, false, true, false, 'published'),
  ('Gem Cascade', 'gem-cascade', 'A polished match-3 puzzler with over 900 hand-designed levels and a low-pressure difficulty curve suited to short breaks.', 'puzzle', 'Match-3', 4.7, 'Android, iOS', 'Cascade Labs', '6.3.4', '340 MB', '2020-09-03', '/assets/games/gem-cascade-cover.svg', '/assets/games/gem-cascade-icon.svg', '["/assets/games/gem-cascade-shot-1.svg","/assets/games/gem-cascade-shot-2.svg","/assets/games/gem-cascade-shot-3.svg"]'::jsonb, 'https://example.com/source/gem-cascade', 'None', true, false, false, true, false, 'published'),
  ('Squad Siege Arena', 'squad-siege-arena', '5v5 team-based shooter with ranked seasons. Ranked season finishers can receive cosmetic and points-based rewards according to the developer''s season pass rules.', 'multiplayer', 'Team Shooter', 4.3, 'Android, iOS, Windows', 'Fireline Studios', '2.9.1', '2.1 GB', '2023-03-11', '/assets/games/squad-siege-arena-cover.svg', '/assets/games/squad-siege-arena-icon.svg', '["/assets/games/squad-siege-arena-shot-1.svg","/assets/games/squad-siege-arena-shot-2.svg","/assets/games/squad-siege-arena-shot-3.svg"]'::jsonb, 'https://example.com/source/squad-siege-arena', 'Points', true, false, true, true, false, 'published'),
  ('Sunny Acres Farm', 'sunny-acres-farm', 'A relaxed farming and decorating game with daily tasks, seasonal events and a cosy pace built for casual sessions.', 'casual', 'Farming Sim', 4.4, 'Android, iOS', 'Meadowlight Games', '3.0.0', '480 MB', '2022-04-27', '/assets/games/sunny-acres-farm-cover.svg', '/assets/games/sunny-acres-farm-icon.svg', '["/assets/games/sunny-acres-farm-shot-1.svg","/assets/games/sunny-acres-farm-shot-2.svg","/assets/games/sunny-acres-farm-shot-3.svg"]'::jsonb, 'https://example.com/source/sunny-acres-farm', 'None', true, false, false, false, false, 'published'),
  ('Lantern of Aeloria', 'lantern-of-aeloria', 'A narrative-driven adventure through a hand-painted world, with light puzzle-solving and a branching story that changes based on player choices.', 'adventure', 'Story Adventure', 4.8, 'Android, iOS, Windows', 'Paper Moon Studio', '1.2.0', '1.6 GB', '2024-07-19', '/assets/games/lantern-of-aeloria-cover.svg', '/assets/games/lantern-of-aeloria-icon.svg', '["/assets/games/lantern-of-aeloria-shot-1.svg","/assets/games/lantern-of-aeloria-shot-2.svg","/assets/games/lantern-of-aeloria-shot-3.svg"]'::jsonb, 'https://example.com/source/lantern-of-aeloria', 'None', false, true, false, false, true, 'published'),
  ('SpinBoard Rewards', 'spinboard-rewards', 'A daily spin-and-earn app built around short mini-games. Points earned can be redeemed through the app''s in-house rewards catalog, subject to its terms.', 'reward-apps', 'Mini-games', 3.9, 'Android', 'Spinnly', '2.1.4', '58 MB', '2024-09-02', '/assets/games/spinboard-rewards-cover.svg', '/assets/games/spinboard-rewards-icon.svg', '["/assets/games/spinboard-rewards-shot-1.svg","/assets/games/spinboard-rewards-shot-2.svg","/assets/games/spinboard-rewards-shot-3.svg"]'::jsonb, 'https://example.com/source/spinboard-rewards', 'Cashback', true, false, true, false, true, 'published'),
  ('Bounty Tap Miners', 'bounty-tap-miners', 'An idle mining and tapping game. Daily bounty tasks feed into a points ledger that the developer converts into gift card rewards on a monthly cycle.', 'earning-games', 'Idle / Tapper', 4, 'Android, iOS', 'Deepvein Games', '1.7.3', '95 MB', '2024-02-10', '/assets/games/bounty-tap-miners-cover.svg', '/assets/games/bounty-tap-miners-icon.svg', '["/assets/games/bounty-tap-miners-shot-1.svg","/assets/games/bounty-tap-miners-shot-2.svg","/assets/games/bounty-tap-miners-shot-3.svg"]'::jsonb, 'https://example.com/source/bounty-tap-miners', 'Gift Cards', true, true, true, false, false, 'published'),
  ('Skyline Drift', 'skyline-drift', 'Night-city drift racing with a heavy customization garage and a photo mode. Ranked drift trials feed a seasonal leaderboard.', 'racing', 'Drift Racing', 4.5, 'Android, iOS', 'Redline Games', '3.3.0', '1.1 GB', '2023-12-05', '/assets/games/skyline-drift-cover.svg', '/assets/games/skyline-drift-icon.svg', '["/assets/games/skyline-drift-shot-1.svg","/assets/games/skyline-drift-shot-2.svg","/assets/games/skyline-drift-shot-3.svg"]'::jsonb, 'https://example.com/source/skyline-drift', 'None', true, false, false, false, false, 'published'),
  ('Word Harbor', 'word-harbor', 'A calm word-search and crossword hybrid with a generous hint system and no timers, aimed at players who want a relaxed puzzle habit.', 'puzzle', 'Word Puzzle', 4.6, 'Android, iOS', 'Harbor Light', '2.0.1', '150 MB', '2021-10-14', '/assets/games/word-harbor-cover.svg', '/assets/games/word-harbor-icon.svg', '["/assets/games/word-harbor-shot-1.svg","/assets/games/word-harbor-shot-2.svg","/assets/games/word-harbor-shot-3.svg"]'::jsonb, 'https://example.com/source/word-harbor', 'None', true, false, false, false, false, 'published'),
  ('Court Kings Live', 'court-kings-live', 'A 3-on-3 basketball game with live seasonal events. Season pass holders can earn tournament rewards tied to end-of-season standings.', 'sports', 'Arcade Sports', 4.2, 'Android, iOS', 'Hardwood Studio', '1.4.0', '780 MB', '2024-03-21', '/assets/games/court-kings-live-cover.svg', '/assets/games/court-kings-live-icon.svg', '["/assets/games/court-kings-live-shot-1.svg","/assets/games/court-kings-live-shot-2.svg","/assets/games/court-kings-live-shot-3.svg"]'::jsonb, 'https://example.com/source/court-kings-live', 'Tournament Rewards', true, false, false, false, true, 'published'),
  ('Outpost Zero', 'outpost-zero', 'A base-building strategy game set on a distant moon. Alliance wars run on a monthly cycle with cosmetic banners for top alliances.', 'strategy', 'Base Building', 4.1, 'Android, iOS, Windows', 'Longhall Interactive', '2.2.5', '1.4 GB', '2022-08-30', '/assets/games/outpost-zero-cover.svg', '/assets/games/outpost-zero-icon.svg', '["/assets/games/outpost-zero-shot-1.svg","/assets/games/outpost-zero-shot-2.svg","/assets/games/outpost-zero-shot-3.svg"]'::jsonb, 'https://example.com/source/outpost-zero', 'None', true, false, false, false, false, 'published'),
  ('Tap Quest Legends', 'tap-quest-legends', 'A tap-to-battle RPG with idle progression. Guild raid participation contributes to an in-game rewards chest distributed weekly.', 'earning-games', 'Idle RPG', 4.3, 'Android, iOS', 'Emberforge', '3.6.2', '410 MB', '2023-05-16', '/assets/games/tap-quest-legends-cover.svg', '/assets/games/tap-quest-legends-icon.svg', '["/assets/games/tap-quest-legends-shot-1.svg","/assets/games/tap-quest-legends-shot-2.svg","/assets/games/tap-quest-legends-shot-3.svg"]'::jsonb, 'https://example.com/source/tap-quest-legends', 'In-game Rewards', true, false, false, true, false, 'published'),
  ('Survey Stacker', 'survey-stacker', 'A rewards app that pairs quick surveys with short puzzle mini-games, converting completed activity into points redeemable in its own store.', 'reward-apps', 'Mini-games', 3.8, 'Android', 'Stackly', '1.3.0', '72 MB', '2024-06-11', '/assets/games/survey-stacker-cover.svg', '/assets/games/survey-stacker-icon.svg', '["/assets/games/survey-stacker-shot-1.svg","/assets/games/survey-stacker-shot-2.svg","/assets/games/survey-stacker-shot-3.svg"]'::jsonb, 'https://example.com/source/survey-stacker', 'Points', true, false, false, false, true, 'published'),
  ('Frostbound Tactics', 'frostbound-tactics', 'A turn-based tactics game set in a frozen kingdom, with permadeath squads and a slow campaign built for careful planning.', 'strategy', 'Turn-Based Tactics', 4.7, 'Windows', 'Cold Hearth Games', '1.0.4', '2.4 GB', '2024-11-01', '/assets/games/frostbound-tactics-cover.svg', '/assets/games/frostbound-tactics-icon.svg', '["/assets/games/frostbound-tactics-shot-1.svg","/assets/games/frostbound-tactics-shot-2.svg","/assets/games/frostbound-tactics-shot-3.svg"]'::jsonb, 'https://example.com/source/frostbound-tactics', 'None', false, false, true, false, true, 'published'),
  ('Rally Rewards Cup', 'rally-rewards-cup', 'An off-road rally racer with a live event calendar. Weekly rally cup rankings determine tournament reward eligibility set by the publisher.', 'racing', 'Rally Racing', 4, 'Android, iOS', 'Muddy Trail Studio', '1.8.0', '890 MB', '2023-09-27', '/assets/games/rally-rewards-cup-cover.svg', '/assets/games/rally-rewards-cup-icon.svg', '["/assets/games/rally-rewards-cup-shot-1.svg","/assets/games/rally-rewards-cup-shot-2.svg","/assets/games/rally-rewards-cup-shot-3.svg"]'::jsonb, 'https://example.com/source/rally-rewards-cup', 'Tournament Rewards', true, false, false, false, false, 'published'),
  ('Block Harmony', 'block-harmony', 'A minimalist block-fitting puzzle with a soothing soundtrack and daily challenge boards.', 'puzzle', 'Block Puzzle', 4.5, 'Android, iOS', 'Quiet Grid', '4.1.0', '48 MB', '2020-02-19', '/assets/games/block-harmony-cover.svg', '/assets/games/block-harmony-icon.svg', '["/assets/games/block-harmony-shot-1.svg","/assets/games/block-harmony-shot-2.svg","/assets/games/block-harmony-shot-3.svg"]'::jsonb, 'https://example.com/source/block-harmony', 'None', true, false, false, false, false, 'published'),
  ('Party Line Trivia', 'party-line-trivia', 'A live multiplayer trivia show app with scheduled rounds. Winning rounds contributes to a points balance redeemable through the app''s rewards partners.', 'multiplayer', 'Party Trivia', 4.1, 'Android, iOS', 'Party Line Media', '2.5.1', '160 MB', '2023-01-08', '/assets/games/party-line-trivia-cover.svg', '/assets/games/party-line-trivia-icon.svg', '["/assets/games/party-line-trivia-shot-1.svg","/assets/games/party-line-trivia-shot-2.svg","/assets/games/party-line-trivia-shot-3.svg"]'::jsonb, 'https://example.com/source/party-line-trivia', 'Cashback', true, false, false, false, false, 'published'),
  ('Petal Town', 'petal-town', 'A gentle town-building and decoration game with no combat and no timers, aimed at players who want a purely creative casual experience.', 'casual', 'Town Builder', 4.6, 'Android, iOS', 'Meadowlight Games', '1.1.2', '290 MB', '2024-08-14', '/assets/games/petal-town-cover.svg', '/assets/games/petal-town-icon.svg', '["/assets/games/petal-town-shot-1.svg","/assets/games/petal-town-shot-2.svg","/assets/games/petal-town-shot-3.svg"]'::jsonb, 'https://example.com/source/petal-town', 'None', true, false, false, false, true, 'published'),
  ('Ruins of Kaldera', 'ruins-of-kaldera', 'An exploration-focused adventure game with light crafting, environmental puzzles and a slow-reveal story across ancient ruins.', 'adventure', 'Exploration', 4.4, 'Android, iOS, Windows', 'Paper Moon Studio', '2.0.0', '1.9 GB', '2022-05-05', '/assets/games/ruins-of-kaldera-cover.svg', '/assets/games/ruins-of-kaldera-icon.svg', '["/assets/games/ruins-of-kaldera-shot-1.svg","/assets/games/ruins-of-kaldera-shot-2.svg","/assets/games/ruins-of-kaldera-shot-3.svg"]'::jsonb, 'https://example.com/source/ruins-of-kaldera', 'None', false, false, false, false, false, 'published'),
  ('Daily Deck Draw', 'daily-deck-draw', 'A card-based earning app where daily deck draws and light strategy battles feed into a points system, redeemable through the developer''s reward catalog.', 'earning-games', 'Card Battler', 4.2, 'Android, iOS', 'Deckwise Games', '1.6.0', '210 MB', '2024-04-03', '/assets/games/daily-deck-draw-cover.svg', '/assets/games/daily-deck-draw-icon.svg', '["/assets/games/daily-deck-draw-shot-1.svg","/assets/games/daily-deck-draw-shot-2.svg","/assets/games/daily-deck-draw-shot-3.svg"]'::jsonb, 'https://example.com/source/daily-deck-draw', 'Points', true, false, false, true, false, 'published'),
  ('Ironclad Frontline', 'ironclad-frontline', 'A large-scale multiplayer shooter with vehicle combat and territory control across 64-player maps.', 'action', 'Shooter', 4.5, 'Windows', 'Fireline Studios', '1.9.7', '3.2 GB', '2023-10-12', '/assets/games/ironclad-frontline-cover.svg', '/assets/games/ironclad-frontline-icon.svg', '["/assets/games/ironclad-frontline-shot-1.svg","/assets/games/ironclad-frontline-shot-2.svg","/assets/games/ironclad-frontline-shot-3.svg"]'::jsonb, 'https://example.com/source/ironclad-frontline', 'None', true, false, false, false, false, 'published'),
  ('PointPocket', 'pointpocket', 'An offer-wall style rewards app centered on quick tasks and playable ads. Completed offers contribute to a balance that can be redeemed for gift cards under the app''s terms.', 'reward-apps', 'Offer Wall', 3.7, 'Android', 'Pocket Labs', '1.0.9', '40 MB', '2025-01-15', '/assets/games/pointpocket-cover.svg', '/assets/games/pointpocket-icon.svg', '["/assets/games/pointpocket-shot-1.svg","/assets/games/pointpocket-shot-2.svg","/assets/games/pointpocket-shot-3.svg"]'::jsonb, 'https://example.com/source/pointpocket', 'Gift Cards', true, false, true, false, true, 'published'),
  ('Circuit Legends Manager', 'circuit-legends-manager', 'A motorsport team management game blending strategy with racing. Season-end standings unlock cosmetic trophies and in-game rewards.', 'racing', 'Racing Management', 4.3, 'Android, iOS', 'Redline Games', '1.3.5', '560 MB', '2024-10-08', '/assets/games/circuit-legends-manager-cover.svg', '/assets/games/circuit-legends-manager-icon.svg', '["/assets/games/circuit-legends-manager-shot-1.svg","/assets/games/circuit-legends-manager-shot-2.svg","/assets/games/circuit-legends-manager-shot-3.svg"]'::jsonb, 'https://example.com/source/circuit-legends-manager', 'In-game Rewards', true, false, false, false, true, 'published')
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  genre = excluded.genre,
  rating = excluded.rating,
  platform = excluded.platform,
  developer = excluded.developer,
  version = excluded.version,
  size = excluded.size,
  release_date = excluded.release_date,
  image_url = excluded.image_url,
  icon_url = excluded.icon_url,
  screenshots = excluded.screenshots,
  source_url = excluded.source_url,
  reward_type = excluded.reward_type,
  free_to_play = excluded.free_to_play,
  featured = excluded.featured,
  trending = excluded.trending,
  popular = excluded.popular,
  new_release = excluded.new_release,
  status = excluded.status;
